In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('predictions.csv')
df.head()

,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,addr1,...,id_35,id_36,id_37,id_38,DeviceType,DeviceInfo,TransactionID,actual,predicted,fraud_probability
0,7864752,107.950,4,7585,553.0,150.0,4,226.0,1,264.0,...,2,2,2,2,1,1735,3303078,0,0,0.101259
1,2260318,37.021,0,3154,408.0,185.0,2,224.0,2,-999.0,...,0,0,1,1,0,1598,3103888,0,0,0.234933
2,10361225,59.000,4,10057,225.0,150.0,2,224.0,2,181.0,...,2,2,2,2,1,1735,3397211,0,0,0.210129
3,5974846,57.950,4,6207,355.0,150.0,4,166.0,2,143.0,...,2,2,2,2,1,1735,3238027,0,0,0.078260
4,4296816,107.950,4,11207,361.0,150.0,4,226.0,2,325.0,...,2,2,2,2,1,1735,3178265,0,0,0.081347

In [5]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    average_precision_score
)

y_true = df['actual']
y_pred = df['predicted']
y_prob = df['fraud_probability']

print("Precision:", precision_score(y_true, y_pred))
print("Recall:", recall_score(y_true, y_pred))
print("F1 Score:", f1_score(y_true, y_pred))
print("PR-AUC:", average_precision_score(y_true, y_prob))
print("\n Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
print("\n Classification Report:\n", classification_report(y_true, y_pred, digits=4))

Precision: 0.17607358624067926
Recall: 0.7827244132591338
F1 Score: 0.2874788945170177
PR-AUC: 0.5460206185022811

 Confusion Matrix:
 [[98837 15138]
 [  898  3235]]

 Classification Report:
               precision    recall  f1-score   support

           0     0.9910    0.8672    0.9250    113975
           1     0.1761    0.7827    0.2875      4133

    accuracy                         0.8642    118108
   macro avg     0.5835    0.8250    0.6062    118108
weighted avg     0.9625    0.8642    0.9027    118108